import = ["~/.config/alacritty/catppuccin-frappe.toml"]

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 13

[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 10}
