# Prefix
set -g prefix M-j
bind M-j send-prefix
unbind C-b

set -sg escape-time 0
set -g mouse on
set -g renumber-windows on
set -g status-position top
set -g status-right ""
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=#d65d0e bold"

# Normal colors in alacritty
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

bind -r C-h resize-pane -L 2
bind -r C-j resize-pane -D 2
bind -r C-k resize-pane -U 2
bind -r C-l resize-pane -R 2

bind n next-window
bind p previous-window

bind N swap-pane -D
bind P swap-pane -U

bind V split-window -v
bind H split-window -h

bind q kill-pane
bind Q kill-window

# Scripts
bind a run "tmux new -dc ~ && tmux switchc"
bind f run "~/scripts/tmux_sesh.sh"
bind W run "~/scripts/tmux_sesh.sh ~/work/synth/vlib"
bind S run "~/scripts/tmux_sesh.sh ~/contrib/systemverilog-homework-private"
bind T run "~/scripts/tmux_sesh.sh ~/test"
