# My tmux config for better keybinds

set -g prefix M-space # Change prefix keybind
unbind C-b
bind M-space send-prefix

bind v split-window -v # Better splits
bind b split-window -h

bind r source-file ~/.tmux.conf # Reload config

set -g mouse on # Mouse mode

bind f resize-pane -Z # Something like fullscreen mode

# Big resize
bind C-h resize-pane -L 5
bind C-j resize-pane -D 5
bind C-k resize-pane -U 5
bind C-l resize-pane -R 5

# Small resize
bind M-h resize-pane -L
bind M-j resize-pane -D
bind M-k resize-pane -U
bind M-l resize-pane -R

# Movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind q kill-pane # Kill pane without confirmation
bind Q kill-window # Kill window without confirmation

bind H swap-pane -U # Swap panes up
bind L swap-pane -D # Swap panes dow

bind S copy-mode # Scroll/select/copy mode

# Change some looks
set -g pane-border-style 'fg=#626880'
set -g pane-active-border-style 'fg=#ea999c'
